# Generated by Django 5.0.7 on 2024-08-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_remove_basichabit_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basichabit',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='basichabit',
            name='time',
        ),
    ]
