# Generated by Django 5.0.7 on 2024-08-16 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_remove_basichabit_frequency_remove_basichabit_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasicHabit',
        ),
    ]
