# Generated by Django 5.0.7 on 2024-08-17 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basichabit',
            old_name='owner',
            new_name='author',
        ),
    ]
