# Generated by Django 5.0.7 on 2024-08-17 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_rename_owner_basichabit_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basichabit',
            name='author',
        ),
        migrations.AddField(
            model_name='basichabit',
            name='owner',
            field=models.ForeignKey(default=999999, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
