# Generated by Django 5.0.7 on 2024-08-23 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_remove_basichabit_author_basichabit_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=100)),
                ('place', models.CharField(default='', max_length=100)),
                ('env_obvious', models.TextField(default='')),
                ('habit_bundling', models.TextField(default='')),
                ('culture', models.CharField(default='', max_length=100)),
                ('figure', models.CharField(default='', max_length=100)),
                ('benefits', models.TextField(default='')),
                ('motivation_ritual', models.CharField(default='', max_length=100)),
                ('habit_shaping', models.TextField(default='')),
                ('reduce_friction', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='basichabit',
            name='adv',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.advancedhabit'),
        ),
    ]
