# Generated by Django 5.0.7 on 2024-08-23 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_advancedhabit_basichabit_adv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basichabit',
            name='adv',
        ),
        migrations.AddField(
            model_name='advancedhabit',
            name='basic',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.basichabit'),
        ),
    ]
