# Generated by Django 5.0.7 on 2024-08-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0015_remove_basichabit_adv_advancedhabit_basic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancedhabit',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='advancedhabit',
            name='culture',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='advancedhabit',
            name='env_obvious',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='advancedhabit',
            name='figure',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='advancedhabit',
            name='habit_bundling',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='advancedhabit',
            name='habit_shaping',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='advancedhabit',
            name='motivation_ritual',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='advancedhabit',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='advancedhabit',
            name='reduce_friction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='advancedhabit',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
