# Generated by Django 5.0.7 on 2024-09-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0017_advancedhabit_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='advancedhabit',
            name='incentive',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='advancedhabit',
            name='progress',
            field=models.TextField(blank=True),
        ),
    ]
